# Making changes? https://github.com/nektos/act may help you test locally

name: Publish for Release

on:
  release:
      types: [released]

jobs:
  publish-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0 # checkout full history for site generation
      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Publish with Gradle
        run: ./gradlew -PdeployRelease=true publish gitPublishCopy
        env:
          ORG_GRADLE_PROJECT_githubPackagesUsername: ${{ github.actor }}
          ORG_GRADLE_PROJECT_githubPackagesPassword: ${{ secrets.GITHUB_TOKEN }}
          ORG_GRADLE_PROJECT_spongeSnapshotRepo: ${{ secrets.SPONGE_MAVEN_SNAPSHOT_REPO_URL }}
          ORG_GRADLE_PROJECT_spongeReleaseRepo: ${{ secrets.SPONGE_MAVEN_RELEASE_REPO_URL }}
          ORG_GRADLE_PROJECT_spongeUsername: ${{ secrets.SPONGE_MAVEN_REPO_USER }}
          ORG_GRADLE_PROJECT_spongePassword: ${{ secrets.SPONGE_MAVEN_REPO_PASSWORD }}
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SPONGE_MAVEN_OSSRH_USER }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SPONGE_MAVEN_OSSRH_PASSWORD }}
          ORG_GRADLE_PROJECT_spongeSigningKey: ${{ secrets.SPONGE_SIGNING_KEY }}
          ORG_GRADLE_PROJECT_spongeSigningPassword: ${{ secrets.SPONGE_SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_spongeKeyStore: ${{ secrets.CONFIGURATE_JARSIGNING_KEY }}
          ORG_GRADLE_PROJECT_spongeKeyStoreAlias: ${{ secrets.CONFIGURATE_JARSIGNING_ALIAS }}
          ORG_GRADLE_PROJECT_spongeKeyStorePassword: ${{ secrets.CONFIGURATE_JARSIGNING_PASSWORD }}
      - name: Publish to GH pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build/gitPublish
